// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tyuiu.oop.ZhukovDA.IsakovAV.StudentHelper.DataModels;

#nullable disable

namespace tyuiu.oop.ZhukovDA.IsakovAV.StudentHelper.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20231116203615_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("tyuiu.oop.ZhukovDA.IsakovAV.StudentHelper.DataModels.Helper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Helpers");
                });
#pragma warning restore 612, 618
        }
    }
}
